apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata: 
  name: back-stack
spec: 
  package: ghcr.io/kroy76/showcase-configuration:latest
  skipDependencyResolution: true
  packagePullPolicy: Always

