apiVersion: backstack.dev/v1alpha1
kind: EKSCluster
metadata:
  name: ${{ values.cluster_id }}
  namespace: default
spec:
  parameters:
    id: ${{ values.cluster_id }}
    region: ${{ values.region }}
    networkSelector: ${{ values.network_type }}
    vpcId: ${{ values.vpcId }}
    subnets: [ ${{ values.subnets }} ]
    spec.compositionSelector.matchLabels[type] : ${{ values.network_type }}
    iam:
      roleArn: ${{ values.iam_role_arn}}
    version: "${{ values.version }}"
    nodes:
      count: ${{ values.nodes_count }}
      instanceType: ${{ values.nodes_instance_type }}
  writeConnectionSecretToRef:
    name: ${{ values.cluster_id }}-kubeconfig
  publishConnectionDetailsTo:
    name: ${{ values.cluster_id }}/${{ values.cluster_id }}-kubeconfig
    configRef:
      name: vault
