apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Software Catalog
  annotations:
    sonarqube.org/project-key: kroy76-backstage
spec:
  type: service
  lifecycle: production
  owner: infrastructure
  system: back-stack